feature: Handle invalid keys on get command
Now the get command returns an handled error when the key does not exist
e.g.:
  get boojack
  error: 'boojack' is not a valid key